baseurl = "/"
languageCode = "en-us"
title = "Jesse Shipley"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 8

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Jesse Shipley"
	description = "Software Developer"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "I'm **Jesse** Shipley. <br> Father, Programmer, and Nerd. <br> Located in the Greater Denver Area."
		# The icons will be shown if you enter your username
		twitter = "Sh1pley"
		github = "Sh1pley"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "jesse-r-shipley"

		copyright = [
			"&copy; Jesse Shipley",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Software Developer located in Colorado"
		content = "Turing School of Software & Design Graduate. Passionate programmer, I just love building cool things."


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			link = "https://github.com/Sh1pley/weather-report"
			thumb = "thumbs/weather.jpg"
			title = "Weather Report"
			description = "Simple weather reporting app. Built in React and Redux."

		[[params.portfolio.gallery]]
			link = "https://github.com/Sh1pley/hot-links"
			thumb = "thumbs/hotlinks.jpg"
			title = "Hot-Links"
			description = "React services app to consume my Rails API. Was done as a 2 part assessment for the final at [Turing](https://www.turing.io/)."

		[[params.portfolio.gallery]]
			link = "https://github.com/Sh1pley/bookchain-react"
			thumb = "thumbs/bookchain.jpg"
			title = "Bookchain"
			description = "App built with Solidity & React. Experimenting with the blockchain."

		[[params.portfolio.gallery]]
			link = "https://github.com/Sh1pley/padcrash"
			thumb = "thumbs/padcrash.jpg"
			title = "Pad Crash"
			description = "Cloned AirBnB with Rails, PostgreSQL, Twilio, Geocoder & Google Maps."

		[[params.portfolio.gallery]]
			link = "https://github.com/Sh1pley/quantified_self"
			thumb = "thumbs/qself.jpg"
			title = "Quantified Self"
			description = "App built with Node, Express, Knex, & PostgreSQL."

		[[params.portfolio.gallery]]
			link = "https://github.com/Sh1pley/Mastermind"
			thumb = "thumbs/mastermind.jpg"
			title = "Mastermind!"
			description = "REPL game made in Ruby. Demonstrates Class inheritance, SRP, and OOP principles."

	[params.recentposts]
		hide  = false
		title = "Recent Thoughts / Outbursts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Networking. And networking. Also jobs (¬‿¬)"

		address = [
			"Fort Collins, CO 80521",
			"United States"
		]
		phone = "303-803-6499"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "jesse.r.shipley@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Lets Talk.."
			submit = "Reach Out"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
  name = "About"
  url = "about"
  weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
